spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  properties:
    hibernate:
      format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
